elastic/elasticsearch-sql-odbc

- driver/defs.h
This PR replaces the now deprecated `xpack` (SQL) API.
> Remove xpack reference

- test/integration/testing.py
This PR fixes the integration testing after the attempt to make `pyodbc` optional, when using the integration framework for loading data into an ES instance only.
It imports and adds the `pyodbc` module as instance member to the testing class: the local scope import alone is insufficient.
> Fix: add pyodbc as instance member to testing class

- CMakeLists.txt
(ci is expected to fail) wait to merge till green light is given.
> bump version to 7.2.1

- CMakeLists.txt
_Do not merge until green light given to bump versions (CI failures are expected)_
> bump version 6.8.2 -> 6.8.3

- CMakeLists.txt
_Do not merge until green light given to bump versions_
> bump version 7.2.1->7.2.2

- dsneditor/EsOdbcDsnEditor/DSNEditorForm.Designer.cs
- dsneditor/EsOdbcDsnEditor/DSNEditorForm.cs
- dsneditor/EsOdbcDsnEditor/DSNEditorForm.resx
This PR adds a new panel to the configuration GUI that allows
controlling of the "rest" of the connection string parameters, i.e. the ones
not yet covered in the existing panels.
> New "Misc" panel for various config options

- CMakeLists.txt
Prepping for version bump.
Do not merge until green light given to bump versions!
> Bump version to 7.3.2

- CMakeLists.txt
Version bump from 6.8.4 to 6.8.5.
> Version bump from 6.8.4 to 6.8.5.

- CMakeLists.txt
Version bump from 7.4.1 to 7.4.2
> Version bump from 7.4.1 to 7.4.2

- CMakeLists.txt
Version bump from 7.5.0 to 7.5.1
> Version bump from 7.5.0 to 7.5.1

- test/integration/elasticsearch.py
- test/integration/ites.py
This PR adds one more option to running the test suite, to instruct
it to rewrite the config file of an existing ES bundle. 
This is just a convenience option.
> Test: add extra behaviour to testing suite

- CMakeLists.txt
_hold merging till ready for release_
> bump version to 6.8.8

- CMakeLists.txt
**_Do not merge until 7.7 has been branched out._**
Bump 7.x to 7.8.0
> Bump 7.x to 7.8.0

- CMakeLists.txt
_DO NOT MERGE UNTIL 6.8.8 IS RELEASED_
> bump version to 6.8.9

- CMakeLists.txt
> Bump 7.7 to 7.7.1

- installer/build/scripts/Build.fsx
Code lifted from GH.elastic/windows-installers#386
> Properly redo looping on TS servers on signing

- CMakeLists.txt
**Do not merge until 7.10.0 is being released**
Bump version at 7.10 release time
> [7.10] Bump 7.10.0 to 7.10.1

- CMakeLists.txt
This is the version bump to 7.10.3 after 7.10.2 was released yesterday. sorry for the delay
> bump version to 7.10.3

- CMakeLists.txt
Bump version for 7.12 release.
> Bump version for 7.12 release

- CMakeLists.txt
This PR executes the version bump for the 7.12.2 release.
> Bump version for 7.12.2

- CMakeLists.txt
Bumping version for 7.13.0 release.
> Bump version to 7.13.1

- CMakeLists.txt
> Bump version to 6.8.17

- CMakeLists.txt
> Bump version to 7.13.2

- CMakeLists.txt
> Bump 7.x to 7.15.0

- CMakeLists.txt
Bump version following 7.15 FF
> Bump version to 7.16.0

- CMakeLists.txt
> Bump version to 6.8.24

- CMakeLists.txt
> Bump version to 7.16.4

- CMakeLists.txt
Bump version to 8.2.0 following feature freeze of 8.1.
> Bump version to 8.2.0

- devtools/3rd_party/licenses/curl-INFO.csv
- devtools/3rd_party/licenses/curl-LICENSE.txt
- devtools/3rd_party/licenses/paket-INFO.csv
- devtools/3rd_party/licenses/tinycbor-INFO.csv
- devtools/3rd_party/licenses/ujson4c-INFO.csv
- devtools/3rd_party/licenses/zlib-INFO.csv
- devtools/3rd_party/licenses/zlib-LICENSE.txt
Update 3rd party releases details.
> Update license info

- .buildkite/branches.sh
- .buildkite/dra-build.ps1
- .buildkite/dra-release.sh
- .buildkite/dra-workflow.trigger.sh
- .buildkite/hooks/pre-command
- .buildkite/hooks/pre-command.ps1
- .buildkite/pipeline.dra.yml
- .buildkite/pipeline.yml
- .editorconfig
- catalog-info.yaml
This will backport the following commits from `main` to `8.9`:
- [Merge pull request #318 from elastic/buildkite-migration](https://github.com/elastic/elasticsearch-sql-odbc/pull/318)
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
> [8.9] Merge pull request #318 from elastic/buildkite-migration

- CMakeLists.txt
Bump version to 9.0.0 in preparation for next major stack version release.
> Bump version to 9.0.0
