elastic/elasticsearch-sql-odbc

driver/connect.c
driver/convert.c
driver/convert.h
driver/defs.h
driver/handles.c
driver/info.c
driver/log.c
driver/odbc.c
driver/queries.c
driver/util.c
driver/util.h
test/connected_dbc.cc
test/test_conversion_c2sql_interval.cc
test/test_conversion_compatibility.cc
test/test_conversion_sql2c_interval.cc

This adds support for the interval types:
- columns and parameters of type interval are now accepted;
- the driver will perform the translation between ES/SQL's ISO 8601
representation and the SQL standard;
- the results/parameters can be converted to/from the permitted data types.

Interval type support

---

driver/catalogue.c
driver/handles.h
driver/info.c
driver/queries.c
driver/queries.h
test/connected_dbc.h
test/test_conversion_c2sql_boolean.cc
test/test_conversion_c2sql_interval.cc
test/test_conversion_c2sql_numeric.cc
test/test_conversion_c2sql_timestamp.cc
test/test_conversion_c2sql_varchar.cc

Currently, in ODBC mode, ES/SQL returns a millis timestamp for "date"
type. This can be negative for datetimes before the Epoch. There's no
standard Win C library function that will work with negative Unix
timestamps, so this commit disables the ODBC for non-catalog statements,
promting ES/SQL to send the "date" as an ISO8601 string.
Additionally add a "client_id" request parameter, to take "odbc32" or
"odbc64" values, depending on the driver build.

ODBC request mode only added for catalog queries. New client_id request param.

---

driver/catalogue.c
driver/connect.c
driver/convert.c
driver/handles.c
driver/handles.h
driver/info.c
driver/log.c
driver/queries.c
driver/queries.h
test/connected_dbc.h
test/test_conversion_c2sql_boolean.cc
test/test_conversion_c2sql_interval.cc
test/test_conversion_c2sql_numeric.cc

This PR fixes the the parameter length handling for strings, when these are converted to
- a number: the driver no longer (incorrectly) expects the string to be 0-terminated (and thus trim the last character);
- an interval: the length of the string is read from a corrected descriptor field.
The binary to interval conversion is now enabled.
The workaround for timestamps, which are now serialized again as ISO8601 string is reverted.
The PR also fixes overwriting of the error message received from the server (with an internal failure message) and adds the (so far missing) ODBC mode to the request JSON object used for connection testing, to have Elasticsearch return an error in case of missing appropriate license.

Fix: parameter length handling, error reporting, timestamp handling

---

dsneditor/EsOdbcDsnBinding/EsOdbcDsnBinding.h
dsneditor/EsOdbcDsnEditor/DSNEditorForm.cs

If the user provides an invalid DSN name (validation by ODBC lib fails),
the driver returns a specific error code. Use this code to return the
user the reason why saving a DSN can't take place.

Provide specific err msg if DSN name is invalid

---

driver/connect.c
test/connected_dbc.cc
test/test_conversion_c2sql_timestamp.cc
test/test_conversion_sql2c_date.cc
test/test_conversion_sql2c_time.cc
test/test_conversion_sql2c_timestamp.cc

ES/SQL renamed the `DATE` type to `DATETIME`, which better conveys the represented data.
This PR applies the same change in the driver.

Change type name from DATE to DATETIME

---

driver/connect.c
driver/error.c
driver/handles.h
test/connected_dbc.cc
test/integration/ites.py

This PR adds initial support for the new DATE ES/SQL (runtime-only) data type (https://github.com/elastic/elasticsearch/pull/37693): the date type will be accepted by the driver and passed onto the application, but no data conversions are possible yet (should applications request them).
The PR also changes the connection testing: the "simple" query has been replaced by data type loading. This improves the testing by setting up the connection just like before "normal" operation would. (Specifically, data types misalignment would no longer be possible, when connection testing would work, but application connecting would later fail.)
A couple of fixes are also addressed:
* incorrect allocation for server version string (the space reservation for the null terminator had been done …

DATE type initial support

---

driver/connect.c
driver/connect.h
driver/defs.h
driver/handles.c
driver/handles.h
driver/queries.c
driver/queries.h
test/integration/data.py
test/integration/install.py
test/integration/ites.py
test/integration/testing.py

With this PR the driver will close a cursor received from ES/SQL
when the statement is closed (i.e. IRD cleared). This should release
faster any resources running against a timer in ES.
An integration test had been added for it as well.
The integration tests "framework" got a new CLI paramter, to force
data-reindexing. Also, the "ephemeral" paramter nwo controls the driver
uninstallation too.
The advertised driver capabilities are also updated to reflect the
progress on ES/SQL side.

Close cursor

---

driver/catalogue.c
driver/catalogue.h
driver/connect.c
driver/info.c
driver/queries.c
test/integration/testing.py

This PR adds support for getting attribute values for current user
and catalog. This is being done by using the now available server-side
corresponding functions.
Close #72.

Support for querying current user and catalog

---

driver/connect.c
driver/defs.h

This PR allows the user to set the page size limit to 0, thus disabling it.
It also increases the default from 10MB to 100MB.
In case the limit is to be enforced, the libcurl callback will now fail faster, skipping a (useless) reallocation (that, until now, allowed copying partial data only before failing).

Allow disabling the cursor page size limit

---

build.bat
test/integration/elasticsearch.py
test/integration/testing.py

ES can take longer to start in a virtualized environment, so increased limits are needed.
`build.bat`: don't set any script variables if only printing the usage (and exit).

Integration testing: increase timeouts for ES starting

---

CMakeLists.txt
driver/connect.c

UJSON4C will fail to parse an object if past the indicated length there's white space => add a 0-terminator.
(The entire parsing in the library is unsafe without this 0-term, actually.)
Close #61.

Workaround UJSON4C's parsing failure cause

---

driver/connect.c
dsneditor/EsOdbcDsnEditor/DSNEditorForm.cs

This PR changes the way the Connect/Save button is enabled:
- the Connect button is now enabled if the hostname field is populated;
- the Save button remains enabled only when both DSN name and hostname are available.
Close #95.

Change Connect button enabling condition

---

driver/odbc.c
driver/queries.c
driver/util.c

Some of the string record fields have been left 0-ed, which is
problematic when their value is asked for. This PR inits them all to
the empty string, so that the transfer can take place.
(Their value would normally be provided by the data source, but this is
now not available with the current ES/SQL API.)
The PR also fixes two API tracing statements.

Init all record fields

---

driver/connect.c
driver/dsn.c
driver/dsn.h
driver/setup.c

"Direct" registry access API was used to read the system info (DSN) on
connection establishment, if received connection string was not
sufficient.
This has now been replaced with existing code that uses ODBC Installer
API instead.
Close #107.

ODBC Installer API for system info DSN access

---

test/integration/install.py

If driver installation fails during integration testing, capture and print the installer log to stdout.

Integration testing: print installer log on failure

---

build.bat
test/integration/install.py

- Uninstall an old driver if present before running the integration
tests.
- Switch on the ephemeral param, removing the drivers and testing
directories at end of (succesful) tests.
Additionally: 
- Check if build type and installation directories are set - and fail
quickly if they aren't - when setting up the development DSN in the
Registry.

Integration testing: uninstall any old driver before attempting a new install

---

test/integration/data.py
test/integration/elasticsearch.py
test/integration/install.py
test/integration/ites.py

This PR replaces the driver uninstalling with `msiexec` (old method) with `wmic` (new method) to avoid the restart manager occasionally signaling the calling process (due to : `RESTART MANAGER: Detected that application with id 21128, friendly name 'Python', of type RmConsole and status 1 holds file[s] in use.`).
Also, add an offline working mode, where the files otherwise downloaded are accessed from a local folder.

Test: driver uninstallation done now with wmic only

---

driver/convert.c
driver/queries.c
test/test_conversion_sql2c_floats.cc
test/test_conversion_sql2c_string.cc

This PR adds two conversion fixes:
- on wide to C string conversion, an incorrect truncation was signaled, due to using the original wide string byte count on evaluating the required output buffer size, instead of the converted string byte count.
- on double conversion to float, the value zero was not considered when checking if the original double is not out of the float range (i.e. `0 < FLT_MIN` lead to an error).

Fix: string and floats conversion fixes

---

driver/connect.c
driver/convert.c
driver/defs.h
driver/dsn.c
driver/dsn.h
driver/handles.h
driver/log.c
driver/queries.c
driver/util.h
test/connected_dbc.cc
test/integration/ites.py
test/integration/testing.py
test/test_conversion_c2sql_timestamp.cc
test/test_conversion_sql2c_date.cc
test/test_conversion_sql2c_time.cc
test/test_conversion_sql2c_timestamp.cc

With this PR the driver will be able to use local timestamps towards
the application and do the translation between that and ES/SQL (UTC).
A connection string parameter controlls if this behavior is enabled; it
is disabled by default.
The timezone is read from the TZ environment variable, or the system if
that isn't set.
The driver will now also provide the SQL format of date/timestamp when a
DATE/DATETIME value is converted to string.

Support for local timezone

---

test/integration/data.py
test/integration/testing.py

This PR will load and use Kibana's sample data sets for the integration testing:
- index the currently three data sets into the local node;
- select and fetch all the columns from the "flights" set.
The "ecommerce" and "logs" sets require server-side changes to be able to use them (i.e. dealing with array fields).

Test: add Kibana's sample data to the tests

---

devtools/3rd_party/dependency_report.bat

This PR adds a Windows alternative to the dependency_report.sh.

Add dependencies reporting batch

---

CMakeLists.txt
driver/connect.c
driver/defs.h
driver/dsn.c
driver/dsn.h
dsneditor/EsOdbcDsnEditor/DSNEditorForm.Designer.cs
dsneditor/EsOdbcDsnEditor/DSNEditorForm.cs
dsneditor/EsOdbcDsnEditor/DSNEditorForm.resx

This PR adds the support for a new connection string paramter,
CloudID.
This is to contain the string offered on Elastic's Cloud administration
page. It facilitates configuring the ODBC connectivity, by having the
driver decode&read from this string Elasticsearch's address and port, as
well as setting the security parameter to the highest value
The config GUI has now a new text field for it. Using this field
disables the input text fields for Hostname, Port and the SSL group.
Reciprocally, if the Hostname field has any text input, that will
disable the Cloud ID field.

Add support for Cloud ID

---

CMakeLists.txt

This PR reapplies #62, but on x86 only.
Fix #133.

Lower ujson4c's stack requirements on x86

---

driver/connect.c
driver/defs.h
driver/dsn.c
driver/dsn.h
driver/handles.c
driver/handles.h
driver/odbc.c
driver/queries.c
driver/queries.h
test/integration/elasticsearch.py
test/test_conversion_c2sql_boolean.cc
test/test_conversion_c2sql_interval.cc
test/test_conversion_c2sql_numeric.cc
test/test_conversion_c2sql_timestamp.cc
test/test_conversion_c2sql_varchar.cc
test/test_conversion_sql2c_floats.cc

This PR adds the DSN configuration and SQL request parameters for:
* the timezone the request should be executed under (relevant for histograms and other time functions);
* the way multi-value fields should be handled by the server.
It also has the integration testing attempt multiple times to enable the trial license and not give up on first error code returned by the server.

Add request params for multi-value fields and timezone

---

test/integration/data.py
test/integration/testing.py

This PR:
* removes some duplicate code for loading the Elasticsearch and Tableau sample data;
* enables testing with the remaining ecommerce and logs sample data available in Kibana.
* adds a new test with Tableau's Batters sample data.

Enable testing with all Kibana sample data

---

driver/connect.c

This PR checks if the Hostname (`server`) configuration begins with `http(s)://` and return a specific error
message if so, to help with a more common config error.
Closes #135

Fail quickly if hostname starts with a HTTP(S) scheme

---

driver/catalogue.c
driver/connect.c
driver/defs.h
driver/dsn.c
driver/dsn.h
driver/handles.h
driver/util.c
driver/util.h
test/connected_dbc.cc
test/integration/testing.py
test/test_util.cc

This PR adds a new connection string parameter to control the escaping of the patern value arguments in catalog functions.
The PVA arguments can use `_` and `%` as special characters to build patern matching values. However, some applications (likely due to some more drivers/DBs misbehaving) use these chars as regular ones, which can lead to ES returning more data than the app intended.
With the auto escaping (on by default), the driver will inspect the arguments and will escape these special characters if not already done by the application. (This is not standards compliant, that's why it's a config option.)
This is the equivalent of https://github.com/elastic/elasticsearch/pull/40661.
The PR also adds more integration tests for the catalog functions.

Introduce auto-escaping of pattern arguments in catalog functions

---

test/integration/testing.py
test/test_conversion_c2sql_timestamp.cc
test/test_conversion_sql2c_timestamp.cc

This PR removes a test from DST suites that was just checking that the chosen test dates have a certain DST applicability. This check fails on machines running on UTC machines.
It also updates the cluster name used in integration tests to what Elasticsearch now advertises in the snapshots: `elasticsearch`.

DST fixes unit test

---

driver/connect.c
driver/convert.c
driver/handles.h
driver/queries.c
test/test_conversion_sql2c_interval.cc

This PR fixes two related issues:
(1) ES/SQL transmits interval values in a ISO8601 period value. An interval-to-period 1:1 mapping is possible, however ES/SQL doesn't adhere to this mapping. For instance:
- instead of `P1DT1H` for `INTERVAL '1 1' DAY TO HOUR`, ES/SQL will send `PT25H` (which in a 1:1 mapping would be `INTERVAL '25' HOUR` literal, equivalent, but different from the original);
- `INTERVAL '61:59' MINUTE TO SECOND` is encoded as `PT1H1M59S` instead of `PT61M59S`;
- `INTERVAL '61' SECOND` is transmitted as `PT1M1S` vs. `PT61S`.
Because of this, the driver will now detect the mapping misalignment, convert any interval in the "day/to/second" range to seconds and re-calculate the values for the corresponding interval members from that.
(2) The interval types with a seconds …

Fix: consider interval's precision. Allow non-aligned period values as interval encoding

---

test/integration/data.py
test/integration/testing.py

This PR adds the tests used by the JDBC driver as protocol tests along ODBC's integration tests. JDBC's tests are lifted from the source, the queries executed through the ODBC driver and the results converted
and compared to values in the tests.

Add JDBC's protocol tests as integration tests

---

test/integration/elasticsearch.py
test/integration/testing.py

This PR adds a few small changes to the integration testing application to:
- allow it to run on non-Windows platforms: the process handling flags and networking exceptions differ in this case;
- relax environment requirements, removing the pyODBC dependency, if not performing tests;
- fix setting up Elasticsearch for testing, swapping the trial-mode activation with password generation blocks, since the former is now password-protected.

Fix integration testing app to run on non-Win platforms. Update ES setup sequence

---

driver/connect.c
driver/connect.h
driver/defs.h
driver/queries.c

This PR adds initial support for the Geo types: shape and point.
The driver will now recognize the new data types and will allow piping through the data as fetched from Elasticsearch, WKT encoded.
Any 3rd party application that will want to work with the type can use their own library on top of ODBC. For existing apps, the driver will return the data as text.

Introduce geo support

---

driver/connect.c
driver/handles.c
driver/queries.c

This PR adds small logging information on what are the timings
involved in getting a reply back from the server:
- the time to first response byte;
- the total time to retrieve the entire response. This should make it
easier to spot the queries that take a longer time to service.
The PR also moves a set of logging statements on a lower level,
allowing to better troubleshoot performance issues by generating less
verbose logs and making them easier to pass around.

Add timing logging for the REST request

---

test/test_conversion_c2sql_timestamp.cc

This PR fixes the unit tests for time to timestamp conversions.
The tests were using the GMT date, while the driver uses the local one
(as per the standard). This led to test failures on systems far "enough"
from GMT, where the date would be different.

Fix time to timestamp conversion unit test

---

driver/handles.c

This PR is simply a partial revert of #162, switching back to debug-level logging for
setting of descriptor fields: one result-set accessing mode requires setting/resetting
of the descriptors for every single cell in a result set, making
info-logging impractical.

Logging: descriptors setting logged back on debug level

---

driver/catalogue.c
driver/connect.c
driver/convert.c
driver/handles.c
driver/info.c

This PR bundles a few minor fixes:
1. A check on conversion failure was incorrectly taking into account the result of a previous column conversion on the same row. The defect was without practical implications, since a second, impossible condition would have had to match to lead to an incorrect failure. However the incorrect first check lead to a failing assertion.
2. The IRD descriptor was not re-init'd on statement handle closing. This defect is fixed just for good house-keeping, since the descriptor would be re-init'd on attaching a new result set to it (which happens regularly when the result for a query is being paged / using a cursor). Along with this, some code duplication has been removed.
3. A few logging statements had the wrong format specifiers, mostly expecting signed, …

Fixes: correct check on truncation failure. Reinit IRD on statement closing. Logging format descriptors

---

CMakeLists.txt
driver/log.c
driver/odbc.c
driver/tracing.h
test/integration/elasticsearch.py

This PR adds the possibility to account for the time the execution
spends within the driver. For that, it simply adds up the ticks
accounted between entering and exiting any ODBC API call.
With it, now one can estimate roughly how much time the driver code
runs, as well as how long the driver waits for the REST calls (previously
available).
This time accounting is done globally and possibly across multiple
threads. Its mostly useful with single-threaded use, though.
The PR also adds the possibility to use a much larger logging
"extended" buffer. This is useful in troubleshooting cases where larger
logging meesages are required (such as when an entire server REST reply
is JSON object is needed).
Both of these features are disabled by default (for all build types).

Enh: trace in-driver execution time. Extended logging buffer

---

CMakeLists.txt
driver/connect.c
driver/convert.c
driver/convert.h
driver/handles.c
driver/handles.h
driver/queries.c
driver/tinycbor.c
driver/tinycbor.h
driver/util.c

This PR extends the CBOR support with the ability to read the
CBOR-encapsulated result sets.
The PR also makes fetching data more efficient with the SQLGetData()
(the alternative to the generally more efficient SQLBindCol()). The
implementation still uses punctual column binding and unbinding, but
SQLFetch() will now cache the source JSON/CBOR object into IRD's records
and will no longer walk the entire list of instantied ARD records all
the way to the ad-hoc bound column.
Counting the total number of rows returned for a query has been changed
to cope with ES's use of indefinite-size arrays, to avoid iterating
twice over the rows in a page.

CBOR support for result sets

---

driver/convert.c
test/test_conversion_c2sql_null.cc
test/test_conversion_c2sql_varchar.cc

This PR fixes the length handling of received wide-char strings as
parameters: the indicator-length pointer of the API call provides the
octet count, so the lenght needs to be divided by wide-char size.
Besides a couple of tests for the fix, the PR adds a new test suite on
null generation (both of non-NULL and NULL types).

fix length read from app ptr when param binding

---

driver/convert.c
driver/util.h
test/test_conversion_c2sql_date.cc
test/test_conversion_c2sql_time.cc

This PR fixes the handling of the columns size of the DATE type parameters.
The previous implementation always expected the size of an ISO8601
timestamp, since DATE and TIME vals area ultimately parsed as a
timestamp. However the column size was passed through unchanged. With
this PR, the size is read as passed in by the application and
adjusted as needed.

Fix handling of size with DATE parameters

---

driver/convert.c
test/test_conversion_c2sql_numeric.cc
test/test_conversion_c2sql_varchar.cc

With this PR the float parameters are no longer sent in the
exponential format, but the default one. With it, the precision of the
sent floats is also increased and respecting the requirements given by
Elasticsearch for each of the float types.

Use default float representation for parameters

---

driver/queries.c
driver/queries.h
driver/util.c

This PR adds the support for sending the parameters encapsulated as
CBOR.
The implementation makes use of the already available parameter conversion
functionality, which prepares the parameter values as strings.
Consequently, except NULL values (and type), the values will be sent as
strings and have the server do a final conversion to the signaled SQL
type (which is actually also the case with JSON).

CBOR support for parameters

---

driver/defs.h
driver/odbc.c
driver/queries.c
driver/util.c
driver/util.h
test/connected_dbc.cc
test/connected_dbc.h
test/test_queries.cc
test/test_util.cc

This PR adds an simple counter of the parameter markers within an
attached SQL statement.
While a correct and complete implementation would require in our case
sending the statement to the server for parameter analysis, this simple
implementation should work for most cases where the application simply
wants to validate the number of user-provided paramters number against
the number of markers in the statement.

SQLNumParams now counts parameter markers

---

test/integration/elasticsearch.py
test/integration/ites.py
test/integration/testing.py

This PR adds a re-run of the integration tests, but carried over
CBOR.
The PR also enables parameter testing, but modifying the "protocol"
tests and adding an equality test with a parameter for each of them; the
paramter is the same value that the tests use to fetch from the server.
With this PR the application now queries the name of the cluster to
match the cataog name against (so that it can be run against nightly
build or a local compmilation easily).

Add CBOR integration testing

---

driver/queries.c
test/test_queries.cc

Fix a c&p error that uses the wrong parameter sizes for estimating the
length of a CBOR request.

Fix CBOR request length estimation

---

driver/queries.c

With this PR `SQLRowCount()` will always return the size of current
row set, also in the case a cursor is present.
The previous implementation returned 0 when a cursor was present, since
the function can't evaluate the total result set size (without actually
fetching it all) and applications shouldn't rely on this result.
The driver - that internally also uses the function for SYS queries -
assumed that ES/SQL will never return a cursor for SYS commands. This
seems however not to be a valid assumption.

SQLRowCount: always return row set size

---

dsneditor/EsOdbcDsnEditor/DSNEditorForm.Designer.cs
dsneditor/EsOdbcDsnEditor/DSNEditorForm.cs
dsneditor/EsOdbcDsnEditor/DSNEditorForm.resx

This PR adds the configuration to the editor form to allow selecting
between JSON and CBOR as data encapsulation.
The text labels on the Misc panel have been left aligned.
Also the Logging and Misc pannels have been swapped, to have Logging
ever so slightly easier to spot.

Add dropdown to select data encapsulation format

---

test/integration/data.py
test/integration/elasticsearch.py
test/integration/ites.py
test/integration/testing.py

This PR adds the functionality to allow the testing framework to
provision and run the tests against a remotely running Elasticsearch
instance.
The '-p' command line option has been modified to take an optional
argument, the URL - optionally with credentials - of the ES instance to
use.

Provision and test against remote ES instance

---

dsneditor/EsOdbcDsnEditor/DSNEditorForm.Designer.cs
dsneditor/EsOdbcDsnEditor/DSNEditorForm.cs

This PR fixes an issue where the testing of a connection or saving
of the DSN failed when the given logging path was invalid (incorrect or
directory missing), even when logging was disabled.
The fix is to simply skip path validation if logging is disabled.
The PR also changes the tab index of the components of each tab
page, so that tab cycling follows the visual order of the elements.

Fix: don't check logging path if logging disabled

---

driver/connect.c
driver/defs.h
driver/dsn.c
driver/handles.c
test/connected_dbc.cc
test/connected_dbc.h
test/test_driverconnect.cc

If the application provides an output buffer for the constructed
connection string, the driver will currently return an error and thus
fail the connection. The correct handling is however to apply truncation
but return the number of characters available without truncation.
This PR works around swprintf() returning an error code, but
otherwise correctly 0-terminating the destination buffer and not setting
the errno.

SQLDriverConnect: fix handling of output connection string buffer 

---

driver/connect.c
dsneditor/EsOdbcDsnEditor/DSNEditorForm.cs

Trim whitespace from `Cloud ID`, `User` and `Hostname` field values before
submitting these to the driver.
(WS is likely to be inserted if copy&pasting these values.)
Also, rephrase the error message presented to the user in case the `Cloud
ID` is incorrect.

Trim whitespace from certain DSN fields

---

installer/build/scripts/Build.fsx

This PR fixes the signature of the MSI signing function, so that it actually gets called.
(The call has been silently ignored so far.)

Fix signing function signature

---

installer/build/scripts/Build.fsx

So far only the MSI had been considered for signing. This commit adds
the logic to also sign the DLL files that are going to be packed into
the MSI.
The PR adds the code to find all the DLL files within the directory
unpackaged from the ZIP file produced by the build, then sign them with
same function used to sign the MSI file.

Sign DLL files to be added into the MSI

---

driver/util.c
driver/util.h
test/test_util.cc

This PR fixes an underrun in the utility function copying a
wide-char string to the client application.
The impact is limited and it can only happen if the
received size of the client buffer is of the wrong size (<=0).
The PR also fixes a logging error happening if this function needs
to truncate the output. The macro for a format specifier with no
precision was provided instead of the needed one with precision. This
could potentially crash the client application in case the string to be
logged in not 0-terminated, logging is explicitely
enabled at an INFO (or higher) level and truncation needs to be applied

Fix buffer underrun for wrong received buffer size

---

CMakeLists.txt
README.md
build.bat
devtools/3rd_party/licenses/zlib-INFO.csv
devtools/3rd_party/licenses/zlib-LICENSE.txt
driver/connect.c
driver/defs.h
driver/dsn.c
driver/dsn.h
driver/handles.c
driver/handles.h
driver/util.c
test/integration/ites.py

This PR adds the option to compress the HTTP/REST payload
(CBOR/JSON):
- zlib is added as a build dependency, libcurl is now compiled against
zlib and zlib is statically linked into the driver DLL;
- a new connection string "Compress" controls the addition of the
Accept-Encoding HTTP header, with possible values "on", "off" and "auto"
(which adds the header if encryption is not enabled);
- the possibility to build and ship libcurl as a dynamic library along
the driver has been removed.
Additionally, this PR switches the default payload format to CBOR.

Enable payload compression

---

dsneditor/EsOdbcDsnEditor/DSNEditorForm.Designer.cs
dsneditor/EsOdbcDsnEditor/DSNEditorForm.cs
dsneditor/EsOdbcDsnEditor/DSNEditorForm.resx

This PR adds a drop-down to allow the payload compression strategy
(one value in: "auto", "on", "off").
The option is encoded in the DSN as the attribute "Compression".

DSN editor: add option for payload compression

---

test/connected_dbc.h

This PR fixes the integration tests past switching to CBOR by
default for the REST body format (#201): the integration tests make use of the
(textual) JSON format, which needs to be enabled in the connection
string used by the simulated connection.

Fix test: force JSON format for tests

---

driver/queries.c

Add the PR adds a the required column backwards compatibility attributes required by 2.x applications and that are not translated by the DriverManager. 
These are simply equivalents of existing 3.x attributes.
Fixes #204

SQLColAttribute: add bwc attributes for 2.x

---

driver/convert.c

This PR initialises a variable ("format") that can be read
uninitialised. There are no negative manifestations of this issue.
---
The var carries the type of time format that has been detected when
parsing a string input value, which would subsequently be converted to
a TIME/DATE/TIMESTAMP data type. In case the source is a string
representing a TIMESTAMP and the destination a DATE, the representation
of the destination is obtained from the original input, by zero-ing the
time part (since this is how DATEs are represented in ES/SQL) and the
"format" var decides, in a disjunction with another variable, on this
action.
In case the source is of the type DATE and the destination also a DATE,
the "format" var would not be set, but its value read. In the case the
random value the var can take …

Fix: init var that's otherwise accessed uninit'd

---

driver/catalogue.c
driver/catalogue.h
driver/connect.c
driver/handles.h
test/test_driverconnect.cc

This PR allows the application set the value of the current catalog attribute, in case this value is the same with what the driver had previously returned for this attribute.
Although Elasticsearch/SQL has no proper catalog support currently, this case should be supported as a safe use of the API.
This currently only works if the attribute had been retrieved before setting, on the same connection; specifically, it won't work when this would be set as a pre-connection attribute.
Closes #211.

Fix: allow (re)setting the current catalog

---

driver/connect.c
driver/defs.h
driver/dsn.c
driver/dsn.h
driver/handles.h
driver/info.c
driver/queries.c
driver/queries.h
test/connected_dbc.cc
test/connected_dbc.h

This PR relaxes the version check the driver does on connect: this
version compatibility is migrated on the server and the driver only
checks that server's version is more recent than a set minimum (that of
the release that applies version policy on the server).
(Related to https://github.com/elastic/elasticsearch/pull/53082)

Prepare the driver to work with newer server releases than its own

---

driver/connect.c

Allow two statment attributes be used on a connection handle.
This is in support of some 2.x applications that can make use of them.
- SQL_ATTR_MAX_ROWS: the value is reset to 0 if different, which is the
same behavior the driver has when the attribute is set on a statement;
- SQL_ATTR_QUERY_TIMEOUT: the attribute is applied; any statement
belonging to the affected connection can subsequently override the
value, so the support is safe.

Allow some statement attributes be used for a connection

---

driver/queries.c
driver/queries.h
dsneditor/EsOdbcDsnEditor/DSNEditorForm.Designer.cs
dsneditor/EsOdbcDsnEditor/DSNEditorForm.cs
test/connected_dbc.cc

This PR switches the default packing mode from JSON to CBOR.
It also always adds the "binary_encoding" boolean field to the REST requests,
which is how the server decides what to answer with (the ES/SQL plugin
overrides the Accept HTTP header).

Switch to CBOR as default packing mode

---

driver/connect.c
driver/convert.c

This PR fixes two low-probability/impact defects:
- when converting a bound parameter from string to an interval type, the destination buffer lacked space for the 0-terminator, which was nevertheless written. This was triggered by unit testing; this functionality has a very low use probability. 
- the recently added support for setting the current catalog came with a defect in the way the catalog (wide) string length was considered: character count vs. the normed byte count. That's now being corrected. This leads to the API call failure, but applications tend to ignore it, thus a low impact.

Fixes: possible buffer overrun on interval conversion. Catalog length handling

---

test/test_driverconnect.cc

Add chunk skipped in #217, adjusting a unit test to use byte instead of
char count for SQLSetConnectAttr() API.

Test: PR#217 complete.

---

driver/handles.c
driver/handles.h
driver/queries.c
test/connected_dbc.cc
test/test_bindparam.cc

Unbound parameters are allowed by the standard and there's a
mechanism that allows the application to signal the driver which
parameters to ignore. There are applications however that set certain
attributes of a first parameter (despite the query containing no
markers), that still don't use this mechanism.
This PR will have the driver ignore parameters with attributes set
by the application, but not bound, as long as these unbound ones don't
show up before the contiguous list of bound parameters.

Params: ignore unbound parameters

---

driver/convert.c
test/test_sqlgetdata.cc

This PR fixes a defect manifesting when getting C-strings with
SQLGetData, in two steps: a first invocation with a 0-space buffer, to
fetch the length of data available, then a subsequent one, with
appropriate buffer size, to actually fetch the data.
The second call would so far fail with "no data available anymore",
since the offset of so-far-read-data was incorrectly updated, also in
the case when no data was actually copied. This commit fixes it, only
updating the offset if there's space in output buffer to copy.
Fetching wide-strings works correctly.
Fixes #220.

Fix: SQLGetData: only update offset if C-string data copied out

---

.gitignore
build.bat
driver/connect.c
driver/defs.h
driver/handles.c
driver/handles.h
driver/log.c
driver/odbc.c
driver/queries.c
driver/util.c
test/integration/install.py
test/test_conversion_c2sql_varchar.cc

This PR changes the way a parameter's SQL type is resolved to an ES
type. So far, the size of the parameter was taken into account, to
select the ES type with the lowest "precision" that would accomodate it.
This worked well so far because IP type was having a precision of 0 (=ignored).
This precision for IP type had been updated in Elasticsearch (to maximum
IP length), which would lead to the driver tagging small length strings
as IP types.
With current change, all string type parameterss are considered as TEXT
types, leaving Elasticsearch/SQL to apply a better, context-informed
conversion.
The PR also extends the size of binary-to-hexa logging and does a better
cleaning with "proper" build script parameter.

Update type selection for string parameters

---

driver/connect.c
driver/defs.h
driver/dsn.c
driver/dsn.h
driver/handles.c
driver/handles.h
driver/queries.c

This PR adds an early execution mode for prepared queries.
Applications generally prepare a statement, optionally reading result
set attributes - like columns count and their characteristics (types and
names) - before executing. A subset of these apps (generally the ones
following older API usage patterns) will fail the entire operation if
these column characteristics aren't available before execution.
Elasticsearch/SQL doesn't support the concept of prepared statements.
What the driver will now do if this mode is enabled (=the new default)
is to execute the query right away, in case this lacks any parameters.
In case the parameter marks are present, the early execution is disabled
for the statement (and potentially the query will fail). However, most
patterns of Elasticsearch/ODBC usage …

Add an early execution mode for prepared statements

---

driver/connect.c
driver/convert.c
driver/handles.c
driver/queries.c
driver/tracing.h

This fixes the debug printing of SQL(U)LEN variable types.
This type is defined as a `long` on WIN32, but a `__int64` on WIN64.
The "%llu"/"%lld" specifier had been used from the start, before the need
for an x86 driver was considered and stayed like that mostly since.
The values logged by an x86 drivers contains the actual values of the
variable, but one needs to convert to hexa, remove the upper 4 byte and
convert back to decimal, which is cumbersome.
The values are now promoted to a `(u)int64_t` in the logging statements,
so printf will always log the correct value.
This change also updates some other few incorrect specifiers.

Fix debug printing of SQL(U)LEN variables

---

dsneditor/EsOdbcDsnEditor/DSNEditorForm.Designer.cs
dsneditor/EsOdbcDsnEditor/DSNEditorForm.cs
dsneditor/EsOdbcDsnEditor/DSNEditorForm.resx

This PR adds two new options to the configuration editor:
- a numerical one, for the [varchar limitation](https://github.com/elastic/elasticsearch-sql-odbc/pull/229);
- a boolean/tick one, for the [early execution](https://github.com/elastic/elasticsearch-sql-odbc/pull/227).
Some of the existing texts for the checkboxes have been updated to have
the question marks removed.
Fixes #234.

Add two new config options to the DSN editor

---

test/integration/testing.py

Following https://github.com/elastic/elasticsearch/pull/54836, ES/SQL will report its non-alias indices as just
`TABLE`, instead of `BASE TABLE`.
This PR adjusts ODBC's tests to that change.

Test fix: update table type to test against

---

test/integration/data.py
test/integration/elasticsearch.py

This PR will have the integration testing app skip verification of
the SSL certificate Elasticsearch server uses (in case of indexing into
an HTTPS URL). This simplifies loading data into nodes with self-signed
or invalid certs.
The PR also now deletes the "old" templates and pipelines before
reindexing.
And finally, it generates indices with changed mappings for
Elasticsearch own test indices to match the field types used in ES
tests. (The "original" indices are still kept since they CSV
reconstruction tests are easier with them.)

Test: don't verify ES SSL cert. Remap ES test data

---

build.bat

This commit pins the chosen VS to 2017. This helps with environments where
multiple versions are installed.

Pin chosen Visual Studio version to 2017

---

installer/build.sh
installer/build/scripts/Commandline.fsx

This also fixes some case sensitive references that were incorrectly
cased and will therefor not be found on *nix systems.

Add a build.sh so installer can be build in *nix systems

---

installer/build/scripts/Build.fsx

This PR adds a few fallback servers that `signtool.exe` will run
against, in case there's an error in the signing process.
It also switches to using the RFC3161 format and SHA256 dig. algorithm.
`signtool.exe` will now be run in debug mode.

Update signing timestamp servers and protocol

---

driver/connect.c

This commit adds info-logging of the credentials (with redacted
password), just like with the rest of the connection properties.
The properties are also debug-logged when the connection string is
parsed, but those messages aren't logged into the per-connection log
file. (The user needs to configure the "alternative logging" to get
those, which is more convoluted.)

Log credentials used to set up a connection

---

test/integration/data.py
test/integration/testing.py

Fixes for running the integration testing app as an ES data provisioning tool:
* In case the '-p' parameter provides a URL to connect to a running
Elasticsearch instance, use that to construct a testing DSN, so another
(and possibly conflicting) '-c' paramter won't need to.
* This also fixes a defect where trying to run the integration suite in
non-indexing mode fails due to missing meta-data.

Testing convenience: build testing DSN out of a provided ES URL

---

README.md
build.bat

Update the CMake generator specs to build with Visual Studio 2019 16 or Visual Studio 2017 15.
The `setup` argument now also takes a year to select between the two versions (ex: `setup:2017`); if none is provided, setting up the environment is sequentially attempted with the two versions above, in the given order.
CMake 3.14 or newer is required for VS2019.
The PR also removes the deprecated `tests` argument.
Closes #248.
Depends on https://github.com/elastic/infra/issues/22063.

Update CMake generation for Visual Studio 16

---

dsneditor/EsOdbcDsnBinding/EsOdbcDsnBinding.vcxproj

VS 2019 will be able to just pick the latest available SDK on the machine and build with it.
Also update toolset to v142.

Retarget project to latest Windows SDK 10 version

---

driver/connect.c
driver/defs.h
driver/dsn.c
driver/dsn.h
driver/handles.h
driver/odbc.c
driver/util.c
dsneditor/EsOdbcDsnEditor/DSNEditorForm.Designer.cs
dsneditor/EsOdbcDsnEditor/DSNEditorForm.cs

This adds support for connection proxying. HTTP, SOCKS4 and SOCKS5 (with
local and remote namem resolution) are supported. Authenticated proxy
access is also possible.
Relates to #273.

Add connection proxying support

---

driver/connect.c
driver/dsn.c
driver/dsn.h
driver/handles.h
dsneditor/EsOdbcDsnEditor/DSNEditorForm.Designer.cs
dsneditor/EsOdbcDsnEditor/DSNEditorForm.cs
dsneditor/EsOdbcDsnEditor/DSNEditorForm.resx
test/integration/elasticsearch.py
test/integration/testing.py

This adds support for authenticating using API Keys.
The DSN editor has been updated to take a new "API Key" field. This field is enabled iif no Username and Password are provided. The field is stored in the DSN string and then used in every request for respective configured connection.

Add support for API Key authentication

---

.buildkite/branches.sh
.buildkite/dra-build.ps1
.buildkite/dra-release.sh
.buildkite/dra-workflow.trigger.sh
.buildkite/hooks/pre-command
.buildkite/hooks/pre-command.ps1
.buildkite/pipeline.dra.yml
.buildkite/pipeline.yml
.editorconfig
catalog-info.yaml

Supporting ESD-6556
Most of the non-pipeline code is copied over from a separate repository where the Jenkins jobs were defined, with slight modifications for Buildkite.
- Add hooks for pulling DRA-related secrets
- Add a pipeline that runs `ctests` on each commit for each active branch
- Add a pipeline that builds and publishes MSI artifacts for DRA
- Add a script that triggers snapshot and staging DRA workflows for each active branch
- Trigger DRA workflows twice per day
The DRA workflow has been tested up to the point of running `release-manager`. It looks like it fails on non-main branches, so I'll have to test after merging. [See here](https://buildkite.com/elastic/bseeders-elasticsearch-sql-odbc/builds/6).

Migrate CI pipelines/workflows to Buildkite

---

.buildkite/branches.sh
.buildkite/dra-build.ps1
.buildkite/dra-release.sh
.buildkite/dra-workflow.trigger.sh
.buildkite/hooks/pre-command
.buildkite/hooks/pre-command.ps1
.buildkite/pipeline.dra.yml
.buildkite/pipeline.yml
.editorconfig
catalog-info.yaml

This will backport the following commits from `main` to `8.10`:
- [Merge pull request #318 from elastic/buildkite-migration](https://github.com/elastic/elasticsearch-sql-odbc/pull/318)
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

[8.10] Merge pull request #318 from elastic/buildkite-migration

---

.buildkite/branches.sh
.buildkite/dra-build.ps1
.buildkite/dra-release.sh
.buildkite/dra-workflow.trigger.sh
.buildkite/hooks/pre-command
.buildkite/hooks/pre-command.ps1
.buildkite/pipeline.dra.yml
.buildkite/pipeline.yml
.editorconfig
catalog-info.yaml

This will backport the following commits from `main` to `7.17`:
- [Merge pull request #318 from elastic/buildkite-migration](https://github.com/elastic/elasticsearch-sql-odbc/pull/318)
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

[7.17] Merge pull request #318 from elastic/buildkite-migration

---

catalog-info.yaml

Test https://github.com/elastic/elasticsearch-sql-odbc/tree/9.0 and other branches for the 9 major version

catalog-info.yaml: enable 9.[0-9]+ branches

---

CMakeLists.txt

(cherry picked from commit 61edba468647a60425cab4a5fba3b77d992873a1)
#	CMakeLists.txt

Fix version qualifier setting in cmake
